steps:
# 1. Database Migration (Alembic) - MUST run before the app is deployed
# This step uses the Cloud SQL Proxy to connect to the database and runs migrations.
- name: 'gcr.io/cloud-builders/gcloud'
  id: Run Migrations
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Install Flask-Script and Flask-Migrate for the manage.py script
      pip install Flask-Script Flask-Migrate
      
      # Use the secret from Secret Manager to set the DATABASE_URL environment variable
      export DATABASE_URL=$$(cat /workspace/secrets/DATABASE_URL)
      
      # Install Cloud SQL Proxy
      wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
      chmod +x cloud_sql_proxy
      
      # Start Cloud SQL Proxy in the background
      ./cloud_sql_proxy -instances=${_CLOUD_SQL_CONNECTION_NAME}=tcp:5432 &
      
      # Wait for the proxy to start
      sleep 5
      
      # Run Alembic migrations (creates the 'User' table )
      python manage.py db upgrade

# 2. Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: Build Image
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ca1-app:$COMMIT_SHA', '.']

# 3. Push the Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push Image
  args: ['push', 'gcr.io/$PROJECT_ID/ca1-app:$COMMIT_SHA']

# 4. Deploy to App Engine Flexible Environment
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy Application
  args: ['app', 'deploy', 'app.yaml', '--image-url', 'gcr.io/$PROJECT_ID/ca1-app:$COMMIT_SHA', '--version', 'v1', '--no-promote']

timeout: '1600s'

# Secrets for the migration step
available_secrets:
- secret: projects/$PROJECT_ID/secrets/DATABASE_URL
  env: DATABASE_URL

# Substitutions for the migration step
substitutions:
  _CLOUD_SQL_CONNECTION_NAME: 'my-ca1-project-2025:europe-west1:ca1-db-instance'
